# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-java
      uses: olafurpg/setup-scala@v6
      with:
        # The Java version to install, a string matching the output format from  `jabba ls-remote`. For example, "adopt@1.8" for the latest AdoptOpenJDK 8 version, "adopt@1.11" for the latest AdoptOpenJDK 11 version, or "graalvm@" for the latest GraalVM version.
        java-version: 11
        # The Jabba version to install.
        jabba-version:  adopt@1.11
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml



